version: "3.9"
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    container_name: "dostavljalecservice"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dostavljalec
  server:
    build: .
    container_name: "server"
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    restart: on-failure
